// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orqwqvhtdvfnxrhctayn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ycXdxdmh0ZHZmbnhyaGN0YXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDU3NjcsImV4cCI6MjA1NzQ4MTc2N30._p795eg5ED30w8-LqPtQd68Pd352hQZ34MeTasO0w8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);